services:
  backend:
    build: ./backend/
    command: /bin/bash -c "python manage.py migrate && python manage.py import_data && gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"