# Generated by Django 4.2 on 2024-09-04 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LevelPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels.level')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerLevelPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата получения приза')),
                ('level_prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels.levelprize', verbose_name='Приз за уровень')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels.player', verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'приз игрока',
                'verbose_name_plural': 'Призы игроков',
            },
        ),
        migrations.CreateModel(
            name='PlayerLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('score', models.PositiveIntegerField(default=0)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels.level')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels.player')),
            ],
        ),
        migrations.AddField(
            model_name='levelprize',
            name='prize',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels.prize'),
        ),
        migrations.AddConstraint(
            model_name='playerlevelprize',
            constraint=models.UniqueConstraint(fields=('player', 'level_prize'), name='unique_prize'),
        ),
    ]
