# Generated by Django 4.2 on 2024-09-04 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='levelprize',
            options={'default_related_name': 'level_prize'},
        ),
        migrations.AlterModelOptions(
            name='playerlevelprize',
            options={'default_related_name': 'player_level_prize', 'verbose_name': 'приз игрока', 'verbose_name_plural': 'Призы игроков'},
        ),
    ]
