# Generated by Django 4.2 on 2024-09-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0002_alter_levelprize_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerlevel',
            name='completed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
