# Generated by Django 4.2 on 2024-09-04 08:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('amount', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'бонус',
                'verbose_name_plural': 'бонусы',
            },
        ),
        migrations.CreateModel(
            name='Boost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('boost_type', models.CharField(max_length=100, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'буст',
                'verbose_name_plural': 'Бусты',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_enter', models.DateTimeField(blank=True, null=True, verbose_name='Время первого входа')),
                ('last_enter', models.DateTimeField(blank=True, null=True, verbose_name='Время последнего входа')),
                ('bonuses', models.ManyToManyField(related_name='players', through='player.Bonus', to='player.boost', verbose_name='Бонусы')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'игрок',
                'verbose_name_plural': 'Игроки',
            },
        ),
        migrations.AddConstraint(
            model_name='boost',
            constraint=models.UniqueConstraint(fields=('name', 'boost_type'), name='unique_boost'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='boost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_boosts', to='player.boost', verbose_name='Буст'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_entries', to='player.player', verbose_name='Игрок'),
        ),
        migrations.AddConstraint(
            model_name='bonus',
            constraint=models.UniqueConstraint(fields=('player', 'boost'), name='unique_bonus'),
        ),
    ]
